spring.application.name=proyecto
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
# Tiempos de espera agresivos para activar el Fallback de inmediato si hay fallo
spring.mongodb.embedded.enabled=false
spring.data.mongodb.connect-timeout=1500
spring.data.mongodb.server-selection-timeout=1500