spring.application.name=proyecto
spring.data.mongodb.uri=mongodb+srv://Casb2904XD:HdBV8ZX9rhfwK6yG@cluster0.rxkteje.mongodb.net/Documentos?appName=Cluster0
spring.mongodb.uri=mongodb+srv://Casb2904XD:HdBV8ZX9rhfwK6yG@cluster0.rxkteje.mongodb.net/Documentos?appName=Cluster0
# Tiempos de espera agresivos para activar el Fallback de inmediato si hay fallo
spring.mongodb.embedded.enabled=false
spring.data.mongodb.connect-timeout=1500
spring.data.mongodb.server-selection-timeout=1500